### ISSUE TITLE
İzin Talep & Takip Sayfası Ekleme

### ISSUE THREAD

**Issue by ymr22** [ymr22/Bil496#5]
Bu sayfaya ana sayfada bulunan menüden erişilecektir. Çalışanlar ve yöneticiler izin haklarını bu sayfadan takip edecek, yönetici eğer bir sorun belirtmediyse izin taleplerini yapabileceklerdir. Eğer yönetici daha önceden izin alınmaması gerektiği ile ilgili bir durum belirttiyse izin alınamayacaktır.

**Comment by ymr22** [comment]
Sayfa tasarımı tamamlandı get/post metotları tamamlandıktan sonra sadece veriler eklenecek.

**Comment by nnilayd** [comment]
Yöneticinin altındaki çalışanların izin taleplerini görüntüleyebildiği ve iznin alınıp alınmama durumuyla ilgili karar belirtebileceği sayfa eklendi.
